name: stpetebeachhouse
favicon: null
layout_spectrum: 0.48947
typography_spectrum: 0.15268
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b5c0c2'
    - '#1c2230'
    - '#848f91'
    - '#454b5b'
    - '#eab372'
  brandStrength: 0.9375
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
